### ISSUE TITLE
From v3.2.1 tag begin the generate excel file open failed, but v3.2.0 is ok

### ISSUE THREAD

**Issue by xkeyideal** [tealeg/xlsx#654] opened 2020-11-30 06:53 UTC
![image](https://user-images.githubusercontent.com/6369390/100577572-7b422c80-331b-11eb-8cb4-12e6144fc17c.png)

macOS 10.15.0

**Comment by xkeyideal** [comment] 2020-11-30 07:10
the warning is Chinese.

the message is  excel file some content has problems, whether let us try to recover? Please click "(Y)"

**Comment by aswjh** [comment] 2020-11-30 07:24
用了DataValidations没有？如果用了，在存储sheet的xml文件里位置不正确会出错。wps能打开，重保存就正确了。

**Comment by xkeyideal** [comment] 2020-11-30 07:38
> 用了DataValidations没有？如果用了，在存储sheet的xml文件里DataValidations位置是不正确的，会出错。wps能打开，重保存就正确了。也可以自己修改源码暂时解决(xmlWorksheet.go中WriteXML函数)。

Thanks for your answer, i will use v3.2.0 temporary and no use `DataValidations`. 

And i recommend using English for others can understand the solution.

**Comment by baloo32** [comment] 2020-11-30 16:52
Same issue here; on creating a (previously working file) the file shows the corrupt workbook message.

Trying to create a file with just the headers - the header row is generated, but the row elements don't seem to have any height, so are hidden (row count looks like it starts from 2 but you can expand row 1 again to see the "missing" row).

**Comment by Nhanderu** [comment] 2021-02-22 21:31
Hi!

I've been having some problems with `DataValidation` that are probably related to this issue. When I remove `sheet.AddDataValidation`, it works just fine, but with it, the same error as @xkeyideal's appears.

The only difference is that it happens with `v3.2.0` and `v3.1.x` too.

**Comment by Nhanderu** [comment] 2021-03-01 00:48
To test whether this had something to do with my data, I cloned the project in my machine and edited the test `TestMakeXLSXSheet/SetDataValidation` (`sheet_test.go:646`) and the same thing happens. No error on the code, but the file fails to open.

I tested it on `master` and `3.2.0`, using Go v1.14, v1.15, and v1.16 (just in case).

I'm on macOS 10.15.7 with Excel for Mac 16.46, but when last week (when I commented here), the file also failed on Windows machines.

I've tried to look for the references for the schema `http://schemas.openxmlformats.org/spreadsheetml/2006/main`, but I couldn't find any ~yet~. Would you have anything that could help me?

Thanks!

**Comment by tealeg** [comment] 2021-03-01 10:58
@Nhanderu the documentation for the schema is actually linked in the README.org for this project - it's here: http://www.ecma-international.org/publications/standards/Ecma-376.htm

Regarding this error - it's rarely related to the data in your sheet, it's usually caused by Excel being very finickity about the ordering of elements in the XML - essentially there are undocumented rules that only Excel knows, or cares about.  That's why you'll often find a file that Excel reports as broken, will work just fine in every other spreadsheet that can read XLSX. 

Anyhow, probably the best approach to fix a bug like this is to extract the xlsx file (they're really just zip files!) and compare the XML before and after Excel has repaired it.  Then hunt down where that XML is being generated and fix it.

**Comment by Nhanderu** [comment] 2021-03-01 11:00
Thanks! I'll try that!

**Comment by tealeg** [comment] 2021-03-01 11:43
Also check if the fix that just landed for data validations affects it.

**Comment by Nhanderu** [comment] 2021-03-05 00:19
It worked! Thanks!

**Comment by tealeg** [comment] 2021-03-05 07:26
@Nhanderu thanks for letting me know!

**Closed by tealeg** 2021-03-05 07:26 UTC
