### ISSUE TITLE
Reading xlsx file with more but one sheet throws panic

### ISSUE THREAD

**Issue by the42** [tealeg/xlsx#278] opened 2017-02-17 16:57 UTC
As of Golang 1.8, Reading a XLSX file with more but one Sheet fails. The issue seems to have been foreseen somehow,

https://github.com/tealeg/xlsx/blob/master/lib.go#L659

but throws now a Panic at this channel write

**Comment by ShawnMilo** [comment] 2017-02-17 17:24
I'm not reproducing this with a file with three worksheets, on Go 1.8 final. @the42, please send an XLSX file I can use to work on this. Thanks!

**Comment by HeinOldewage** [comment] 2017-02-19 16:48
A data race exists surrounding that channel. 
I have been away of it for some time, but the only time it should panic is if a workbook has two sheets in, with both containing errors. 
Some timing changes might have happened in go1.8 making the case more likely.  
Reading the workbooks should be rewritten to a more idiomatic way. This will be some work though.

Example test case that breaks:
````
go test -race -tags=fuzzy -test.seed=1487522509
````

I will see if I can find a nice refactor for the code.

**Comment by the42** [comment] 2017-02-19 19:39
Coming back to your request to duplicate the error / provide an XLSX-file. I think what raised my issue is somehow related to the already fixed #275:

- I created an XLSX-file using Libreoffice - no issues reading the file with tealeg/xlsx
- I opened the file using Excel 2010 (on Windows), added another sheet, added data, saved the file

I guess what has happened then was that this file triggered for both sheets the error in #275 which (as you identified) triggers the race condition.

The switch to Go1.8 was likely only coincidence.

**Comment by tealeg** [comment] 2017-02-19 20:12
@the42 thanks for reporting the bug.  I'll close this for now as it seems related to the two issues we've recently merged fixes for.  Don't hesitate to reopen the issue should it reoccur.

**Comment by tealeg** [comment] 2017-02-19 20:13
@HeinOldewage pretty sure the combination of your fix and the one I did on Friday have cleared this up.  Thanks a lot for your work!

**Comment by tealeg** [comment] 2017-02-19 20:13
@ShawnMilo looks like we've killed this one.  Thanks for monitoring this stuff!

**Closed by tealeg** 2017-02-19 20:13 UTC
Labels: needs more info
