### ISSUE TITLE
Interrupting a program without saving a file corrupts it / no close function

### ISSUE THREAD

**Issue by tbourvon** [tealeg/xlsx#144] opened 2015-07-14 09:14 UTC
This is not the issue by itself, the issue is that I HAVE to call Save() to properly close a file while I could be willing to discard it upon program interruption, for example with `defer file.Close()`.
We need a proper function on the File struct to close it without saving.

**Comment by tealeg** [comment] 2015-07-14 09:22
@BurningMind I'm somewhat surprised that not closing a file we're reading, but not writing to would corrupt it.  Can you provide a sample program that causes this issue to occur?

**Comment by BurningMind** [comment] 2015-07-14 11:15
package main
    
    import (
    	"fmt"
    
    	"github.com/tealeg/xlsx"
    )
    
    func main() {
    	path := "C:\\Users\\trist_000\\Desktop\\Disposal\\BOI - IGF serials - Copy.xlsx"
    
    	fmt.Print("Press Ctrl-C right now")
    
    	file, err := xlsx.OpenFile(path)
    	// Uncomment to fix
    	//defer file.Save("")
    	if err != nil {
    		panic("error loading file")
    	}
    
    	var input string
    	fmt.Scanln(&input) // Use Ctrl-C here
    
    	file.Save(path)
    
    	fmt.Println("Done!")
    }

**Comment by HeinOldewage** [comment] 2015-07-14 11:38
The problem is not with `xlsx.OpenFile` but with `file.Save(path)`.
Change the following in the example

    var input string
    fmt.Scanln(&input) // Use Ctrl-C here
    fmt.Println("About to save")
    file.Save(path)

The program will print out "About to save" if one presses Ctrl-C. `fmt.Scanln()` exists with an `EOF` error and `file.Save(path)` is executed(at least partially). Adding the defer statement changes program flow. Removing `file.Save(path)` also solves the problem.

The best solution is not to save to the file one is reading from. Save to `path+"~"` and after that is successful, copy it over the original and delete the temp, then there is at least one valid copy(either before or after edit) of the data on disk.

**Comment by BurningMind** [comment] 2015-07-14 12:19
This is only a workaround, not a solution.

The solution here would be to fix the Save() function.

**Comment by HeinOldewage** [comment] 2015-07-14 13:46
I misunderstood your issue. As I understand it now, you want to close the `xlsx.File` to free memory and file handles?

If that is the case take note of the following: 
`xlsx.OpenFile()` Both Opens and Closes the underlying file (`os.File`) before returning a `xlsx.File`.
There is no open handle to a file once `xlsx.OpenFile()` returns, there is nothing to close. 
`file.Save()` Reopens a handle to the file , writes the data and closes the handle. There is nothing to close after it returns.

If this does not solve your problem please explain, why you think the file/library does not properly close or what you would like the new Close function to do.

**Comment by BurningMind** [comment] 2015-07-14 17:10
No, the problem is that saving a file without writing to it corrupts it. This is what my example demonstrates. Save needs to be fixed.

**Comment by tealeg** [comment] 2015-07-20 08:54
@BurningMind forgive me if I'm wrong, but it seems like we're now talking about two different issues.  You said initially that exiting the program without calling Save() corrupts the file, now you're saying that calling Save() without writing to the file corrupts it (this seems plausible - actually modifying an existing file at all is a very risky operation with this library as it stands today).  Do both issues exists, or is this just your understanding of the problem changing?

**Comment by BurningMind** [comment] 2015-07-20 09:14
I'm sorry I haven't been clearer. As @HeinOldewage pointed out, it seems that my initial diagnostic was wrong, and the the problem lies with calling the Save() function when nothing has been written to the file (this seems to corrupt the file).

**Comment by tealeg** [comment] 2015-07-20 09:43
@BurningMind OK, great.  As I mentioned before, that makes more sense to me.  Probably there's a sensible solution in terms of a "modified" flag.  In which case Save() would be a NoOp for files that pre-existed.

**Comment by BurningMind** [comment] 2015-07-20 09:57
Wouldn't it be better to understand why the saved file gets corrupted? I'm far from being an xlsx specialist, but I can try and come up with a Pull Request if I can figure out the problem. Else we'll just go with your solution which far more convenient.
Does that sound good to you?

**Comment by tealeg** [comment] 2015-07-20 10:04
@BurningMind well, it really depends on what you mean by "corrupted" - if the definition is only that it doesn't open in Excel, then I'm afraid there are some well established problems on that front.  The load/save routines are not symmetric, and actually in most cases, loading an re-saving an XLSX document is a lossy operation right now.

The fix I suggest above is, as you say, no fix at all, but it's a pragmatic short term fix for simplistic cases. 

I have a long term goal of having the library be able to open a document, make modifications and rewrite it in a way that is lossless and reliable, however that it is still a long way off and relies on some other tooling that I am working on in the background.

**Comment by BurningMind** [comment] 2015-07-20 10:10
@tealeg the corruption I'm talking about is the file weighing 0kb (at least that's what Windows Explorer tells me) after this modification-less save. I doubt this is just a "lossy" save, this looks much closer to a logic flaw in the saving/writing process.

I'll take a look at all of this in the evening, and I'll come back to you with that I've found. If the cause is the lossy save, then I guess the best fix is your workaround.

**Comment by tealeg** [comment] 2015-07-20 12:21
@BurningMind OK, that doesn't sound odd.  Let me know what you find out.

**Comment by BurningMind** [comment] 2015-07-27 06:43
Hello again. Surry, but I couldn't find the cause of this issue. I tried
narrowing it down but it didn't amount to much (also I didn't have as much
time as I wanted for it), so I believe that your solution should be what we
implement to fix the problem.

**Comment by tealeg** [comment] 2019-11-02 06:41
It seems like this is about the program exiting mid-operation.

**Closed** 2020-04-09 00:01 UTC
Labels: no-issue-activity, triaged
