### ISSUE TITLE
many rows xlsx run out of memory 

### ISSUE THREAD

**Issue by xiao-xiao-xiao** [tealeg/xlsx#512] opened 2019-12-21 09:45 UTC
[testlargefile.xlsx](https://github.com/tealeg/xlsx/files/3991249/testlargefile.xlsx)
this file hava many rows and cols  need  a large of memory ,

below function can support ?
```go
OpenFileWithCtx(ctx context.Context, path)(*File, error)

ctx, cancel := ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
defer cancel()
f, err := OpenFileWithCtx(ctx, path)
```

**Comment by tealeg** [comment] 2020-03-24 07:03
@xiao-xiao-xiao having a `context.Context`, whilst useful sometimes, is not actutally the answer here (it only allows us to fail more gracefully). 

In the current `master` version of the project (which will be released as v2.1.0, but which you can already import as `"github.com/tealeg/xlsx/v2"`) you can set the `OpenFile` method to use a disk based cell store in order to avoid exhausting system memory:

```go
...

import "github.com/tealeg/xlsx/v2"
...

f, err := xlsx.OpenFile(path, xlsx.UseDiskVCellStore)
```

I will consider adding context to the high level operations though, because I see that it can be important.  It will be non-trivial though.

**Comment by RoomFor2nds** [comment] 2020-04-01 16:08
@tealeg UseDiskVCellStore is working great when constructing the file, but `file.Save()` seems to read the entirety of the file into memory, defeating the purpose of using DiskV. Is this the intended behavior when saving a file using DiskV storage?

**Comment by tealeg** [comment] 2020-04-02 04:14
@RoomFor2nds no, that's an oversight on my part.  I've created a new issue #539 to address that.

**Closed** 2020-04-27 21:33 UTC
