### ISSUE TITLE
Support classic XLS

### ISSUE THREAD

**Issue by masterkorp** [tealeg/xlsx#205] opened 2016-03-16 16:30 UTC
Hello,

Does this library support the classix XLS format?

**Comment by ShawnMilo** [comment] 2016-03-16 16:36
No. This is a duplicate of #25.

The XLS format is a binary one, and XLSX is XML. They are completely different and can't be supported by the same code.

I've used this for a simple need and it worked for me: https://github.com/extrame/xls

**Closed by ShawnMilo** 2016-03-16 16:36 UTC

**Comment by masterkorp** [comment] 2016-03-16 16:38
@ShawnMilo thank you. Sorry for the duplicate entry.

**Comment by ShawnMilo** [comment] 2016-03-16 16:40
No worries. I hope I didn't come across too harsh there. It's a reasonable question for most people. A search of the issue history would have brought it up (which is how I found it), but it's not like it was a hassle for me to look it up and reply. Happy Tuesday.
