### ISSUE TITLE
has unexpected file github.com/tealeg/xlsx-2.0.0/cell_test.go

### ISSUE THREAD

**Issue by mikepenson** [tealeg/xlsx#580] opened 2020-06-16 12:46 UTC
go: downloading github.com/tealeg/xlsx v2.0.0
go get github.com/tealeg/xlsx: zip for github.com/tealeg/xlsx@v2.0.0 has unexpected file github.com/tealeg/xlsx-2.0.0/cell_test.go

**Comment by tealeg** [comment] 2020-06-16 13:42
v2.0.0 is a known broken release, v2.0.1 was tagged to fix it.  I'm not sure if that's the cause of the issue, but i'd start there.  Unless you have a reason not to I'd also strongly advise moving to v3.

**Closed** 2020-06-19 09:12 UTC
