### ISSUE TITLE
Opening an xlsx file and saving it as another xlsx file creates an invalid file

### ISSUE THREAD

**Issue by manuviswam** [tealeg/xlsx#133] opened 2015-07-02 12:02 UTC
``` go
package main

import (
    "fmt"
    "github.com/tealeg/xlsx"
)

func main() {
    var file *xlsx.File
    var err error

    file, err = xlsx.OpenFile("/path/to/file.xlsx")
    err = file.Save("/path/to/anotherFile.xlsx")
    if err != nil {
        fmt.Printf(err.Error())
    }
}
```

The above code compiles and runs fine. It creates anotherFile.xlsx but when opening this file Excel application crashes.

**Comment by Immortalin** [comment] 2015-07-06 04:50
@tealeg I also faces this issue. However in my case office 2010 was able to "repair" the file. My suggestion is to add a file.SaveOpenFile method and utilize (this)[https://golang.org/pkg/os/#File.Close] to close a file after writing to it.

**Comment by ShawnMilo** [comment] 2015-07-06 08:11
I am not able to duplicate this with LibreOffice.

@manuviswam: Are there any error messages from Excel?

@Immortalin: Can you provide an example of a very simple .xlsx file before and after the repair process, so I can see what the difference is?

**Comment by tealeg** [comment] 2015-07-06 08:37
@ShawnMilo you can almost never reproduce such errors with LibreOffice - it has a much more liberal parsers.  In most cases these issues stem from small variances in what is output from what the XSD defines (noting, for example that element ordering is important for Excel to consider a document valid). 

For what it's worth - eliminating this kind of problem is one of the reasons I've started work on some XSD work.  As Shawn is doing an excellent job here, I'm trying to use my spare cycles to progress that work and fix the big problem rather than worrying about all the small ones ;-)

@Immortalin I'm not really sure I understand your suggestion.  Did you think that the file was missing some data that hadn't been flushed to it?  There isn't a general problem with the validity of files, per se, it is only that Excel has an extremely picky validation process and is actually terrible at telling you what the real error is.   The before and after version of the files are the best way we currently have of seeing what's really wrong.

**Comment by tealeg** [comment] 2015-07-06 08:39
Note also that this is essentially a duplicate of #53 - however that is only because Excel doesn't given us sensible error messages in these cases.

**Comment by manuviswam** [comment] 2015-07-06 08:53
@ShawnMilo I am also able to repair it with the latest version of MS Office
Please find the sample files below
[Before repair](http://wikisend.com/download/289624/Output.xlsx)
[After Repair](http://wikisend.com/download/113338/OutputAfterRepair.xlsx)

**Comment by Patrick-H** [comment] 2015-07-07 08:28
I have similar problems. I cannot open the any files saved by this package. I use Excel 2013.

I think there's big bugs with saving files. Hope to upgrade soon!~~ I need it urgently. lol

**Comment by Patrick-H** [comment] 2015-07-07 08:33
File1: http://wikisend.com/download/273508/test-before.xlsx
File2: http://wikisend.com/download/378616/test-after.xlsx

I opened File1 and saved to File2, but I cannot open File2 via Excel 2013.

**Comment by Patrick-H** [comment] 2015-07-07 08:33
I have similar problems. I cannot open the any files saved by this package. I use Excel 2013. I think there's big bugs with saving files. Hope to upgrade soon!~~ I need it urgently. lol

Testing:

File1: http://wikisend.com/download/273508/test-before.xlsx
File2: http://wikisend.com/download/378616/test-after.xlsx

I opened File1 and saved to File2, but I cannot open File2 via Excel 2013.

**Comment by shawnye** [comment] 2016-01-23 17:47
Agree with @Patrick-H 
It seems it can NOT save as other files properly (just like copy), no error prompted, but the file has changed , I found it may fail to keep original styles or set invalid styles.

**Comment by tealeg** [comment] 2016-02-19 21:03
@shawnye @Patrick-H  - I'm sorry to tell you that without a major rework of both how we do XML I/O and  how we round-trip from the XML to the user oriented interface of this library, I doubt we'll get to the point where it's safe to open an existing file and modify it.

**Comment by ShawnMilo** [comment] 2016-03-17 16:16
@manuviswam @shawnye @Patrick-H 

Would you please check this problem against this branch and let us know if it is fixed?

https://github.com/tealeg/xlsx/tree/fix-styles

**Comment by manuviswam** [comment] 2016-03-17 16:29
Still having issues
Please find the relevant information
[output file](https://github.com/tealeg/xlsx/files/178258/anotherFile.xlsx)
![Error recovered](https://cloud.githubusercontent.com/assets/6387988/13853148/6e4b8002-ec8b-11e5-9fbf-bb9404b09a47.JPG)
[source file](https://github.com/tealeg/xlsx/files/178259/test.xlsx)

**Comment by manuviswam** [comment] 2016-03-17 16:33
On a simple file, it is not showing any issues now. I didn't test it extensively though.

**Comment by ShawnMilo** [comment] 2016-03-17 16:37
@manuviswam 

Thanks for getting back to me so fast! I I will check out the files you sent me. I don't see them in this conversation (on github), but I did receive them by e-mail.

**Comment by manuviswam** [comment] 2016-03-17 16:38
It fails when there is a simple sum() in the sheet.
error log as follows,
```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error036880_01.xml</logFileName>
<summary>Errors were detected in file 'D:\anotherFile.xlsx'</summary>
-<removedParts summary="Following is a list of removed parts:">
<removedPart>Replaced Part: /xl/worksheets/sheet1.xml part with XML error. Load error. Line 2, column 0.</removedPart>
</removedParts>
</recoveryLog>


```

[source file](https://github.com/tealeg/xlsx/files/178277/test.xlsx)
[output](https://github.com/tealeg/xlsx/files/178276/anotherFile.xlsx)

**Comment by manuviswam** [comment] 2016-03-17 16:39
@ShawnMilo Please ignore the deleted comment. It was a mistake.

**Comment by ShawnMilo** [comment] 2016-03-17 16:40
Okay. That's why I couldn't find it here. I'll ignore those files and just look at those in your post about the `sum()` problem.

**Comment by tealeg** [comment] 2019-11-02 06:31
It's 4 years since this was opened.  No activity in 3.  I'm closing it as out of date.  If the problem still exists and you still want a fix, feel free to reopen it.

**Closed by tealeg** 2019-11-02 06:31 UTC
Labels: in progress
