### ISSUE TITLE
is there a way to read big xlsx file?

### ISSUE THREAD

**Issue by easykoo** [tealeg/xlsx#109] opened 2015-04-26 15:22 UTC
Hi 
I try to read a xlsx file which is exceed 10MB, it's stuck.
is there a way to not read blank rows?

Regards

**Comment by ShawnMilo** [comment] 2015-04-26 15:26
Can you post the file somewhere? I don't think you can arbitrarily skip data while reading, but maybe we can figure out what the slowdown is. 10MB doesn't seem very big. Do you get any error messages, or does it just hang? Do you notice if it's using a lot of memory, CPU, or neither?

**Comment by tealeg** [comment] 2015-04-27 08:30
@ShawnMilo FWIW, I suspect the issue is not the file size.  You can make an arbitrarily large XLSX file and the file format will omit the empty cells so that 10MB file could have millions of empty cells in it.  Inside the library we expand that back out again, which could result in 1. a very long loop and 2. a very high memory usage.  This always fell, for me, under the category of things I'd fix if I found time to do an xlsx 2.0 ;-)

**Comment by ShawnMilo** [comment] 2015-04-27 17:08
@tealeg Thanks. I'll have a look if we get a sample file. But if, as you suggest, it's not something easily addressed in the current codebase, then maybe it'll just have to be a flaw for now. I'd consider millions of empty rows to be an abuse of the data format anyway.

**Comment by nemtsevp** [comment] 2015-10-05 13:14
Hi.
I have similar issue. File made in unknown program, i guess, MsExcel. When read file, sheet struct contains only first row. If i open it with LibreOffice 4.4 and save it as another copy, resulting file have even larger size, but can be processed properly.
https://drive.google.com/file/d/0BzuCv0izFbN-dkpORFp3Y21mYXM/view?usp=sharing

**Comment by tealeg** [comment] 2019-11-02 05:45
This is on the list of burning issues I'd like to at least partially addres.

**Comment by tealeg** [comment] 2020-03-08 21:31
As of right now, the `master` branch of this repo support passing the `xlsx.UseDiskVCellStore` as an `xlsx.FileOption` to all functions that return an `xlsx.File` struct.  Doing so causes the disk to be used as a backing store for rows and cells and thus allows you to process an arbitrarily large number of them (trading memory use for temporary disk use, and slightly lower performance).

**Closed by tealeg** 2020-03-08 21:31 UTC
Labels: triaged
