### ISSUE TITLE
invalid memory address or nil pointer dereference for big xlsx

### ISSUE THREAD

**Issue by abutre** [tealeg/xlsx#114] opened 2015-05-27 01:08 UTC
Hello,

A big xlsx file that previously was loaded ok, after update of xlsx, is failing with this error.
Was any change made to code to limit the size of loadable files ?

Ricardo.

**Comment by abutre** [comment] 2015-05-27 01:38
It only occurs if using a version after commit a5130fdb656a3144617e553ac0ea645add12a940.
I am now using 10e0b59601ffdf1152c1e0d935c16dd15a80316d, and the file is loaded.

**Comment by ShawnMilo** [comment] 2015-05-28 14:50
None of the code explicitly sets any limits. Can you post an Excel file and code that shows the problem? Also, have a look at #109. Is this problem a duplicate of that one?

**Comment by abutre** [comment] 2015-05-28 18:11
I will send you zip with an example that  with xlsx on "master" it generates the error. Checking out commit 10e0b59601ffdf1152c1e0d935c16dd15a80316d, it works.
Where

**Comment by ShawnMilo** [comment] 2015-05-28 18:12
Thanks, @abutre. Please include a very small sample program that demonstrates the program as well.

**Comment by abutre** [comment] 2015-05-28 18:13
https://drive.google.com/file/d/0B_h7s0ZrsVVVSE5zYlN4WktMRDg/view?usp=sharing
There you have code and xlsx

**Comment by ShawnMilo** [comment] 2015-05-28 20:03
@abutre: I have a workaround and possible permanent fix.

Please see PR #117.

**Comment by abutre** [comment] 2015-05-29 09:50
Thank you @ShawnMilo ! Fix for #117 worked ! I will disable google drive share.
Will it be merged into master ?

**Comment by ShawnMilo** [comment] 2015-05-29 14:34
@abutre, you're welcome! I'm glad it solved your problem.

Yes, it will be merged after I find a way to add a test to prevent a regression.

**Closed** 2015-06-01 12:23 UTC
Labels: in progress
