### ISSUE TITLE
Write Broken?

### ISSUE THREAD

**Issue by scohen28** [tealeg/xlsx#80] opened 2015-01-19 18:07 UTC
Did a go get -u to refresh, now the Writing functionality doesn't seem to work anymore - I'm using the sample program provided - workbook is created by is unreadable:

"Excel could not open MyXLSXFile.xlsx because some content is unreadable  Do you want to open and repair this workbook?"

I'm on a Mac, Excel is 2013.  This worked back in December, so something has changed - I'll start grabbing earlier commits and report back if I find one that works vs broken.

**Comment by scohen28** [comment] 2015-01-19 18:13
FYI - the the testdocs/ folder, testfile.xlsx and testrels.xlsx both display the same error message, the other files load/display fine.

**Comment by tealeg** [comment] 2015-01-20 01:17
This is a duplicate of the issues tracked in #63, please comment there if you find out anything more.

**Closed by tealeg** 2015-01-20 01:17 UTC
